name: Deploy Lambda using CDK

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python 3.12
        uses: actions/setup-python@v3
        with:
          python-version: '3.12'

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m venv .env
          source .env/bin/activate
          pip install -r requirements.txt
          pip install aws-cdk.aws-lambda aws-cdk.aws-iam aws-cdk.aws-logs

      # Build and synthesize the CDK app
      - name: Build and synthesize CDK app
        run: |
          source .env/bin/activate
          cdk synth

      # Deploy the CDK app
      - name: Deploy CDK app
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1
        run: |
          source .env/bin/activate
          cdk deploy --require-approval never
